name: quest_hunt
version: 0.1.0
publish_to: none

description: Ein NFC Schnitzeljagd-Spiel in Flutter.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
